### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Majke882** [m4reQ/Oss-2.0#1]
![hehe](https://user-images.githubusercontent.com/53983698/62827699-d5722800-bbd4-11e9-9d1e-c26956fd342e.png)

**Comment by Majke882** [comment]
![Bez tytułu](https://user-images.githubusercontent.com/53983698/62827721-41ed2700-bbd5-11e9-850c-e79a618ef0a0.png)

**Comment by m4reQ** [comment]
Changed order of imported modules.
